package:
  name: ties_ana
  version: 0.0.0

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - setuptools
  run:
    - python
    - numpy
    - scikit-learn
    - six
    - pymbar

about:
  home: https://github.com/adw62/TIES_analysis
  license: 'LGPL'
