name: publish_conda

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish on conda

    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: adw62/conda-package-publish-action@v1.1
      with:
        subDir: devtools/conda-recipe
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}